### ISSUE TITLE
Reset des mots de passe

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-annuaire#35]
Trouver un moyen de pondre une ihm pour faire un reset du mot de passe.
Cette fonctionnalité est accessible pour l'admin étab et le superuser.

Question  : faut-il faire en sorte que l'admin qui l'utilise puisse mettre ce qu'il veut ?
Faut-il imposer quelque chose ?

**Comment by SamSuffit** [comment]
Après discussion:
 - mot de passe par default est maintenant l'uid de l'utilisateur
 - l'interface d'admin doit afficher le mot de passe par default si le mot de passe est le mot de passe par defaut

Pas de traitement de reprise
