### ISSUE TITLE
Mettre un accent aigü sur le nom du profil "Elève"

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-annuaire#86]
car sinon le profil "élève" n’apparaît pas dans les résultats de recherche des utilisateurs (admin-panel)
cf capture
![capture du 2016-07-08 15-45-18](https://cloud.githubusercontent.com/assets/7963908/16689440/44c01a54-4523-11e6-858b-1e528115f783.png)

**Comment by heleroy** [comment]
La recherche ne fonctionne que si on écrit "elève" vu que le nom du profil est enregistré sous "Elève".

**Comment by dlacroix** [comment]
je ne reproduit pas le problème aujourd'hui
